router-fix
ruxailab/RUXAILAB pull request #362
Opened 2024-03-08 16:43 UTC by skushagra9

#303

2024-03-08 16:45 UTC, skushagra9 commented
I have made the changes in the mods
and the changes in the modified are to help users set it up locally
You can ignore if not needed

2024-03-08 16:45 UTC, skushagra9 commented
I will add the toast message

2024-03-12 23:06 UTC, KarinePistili requested changes
We would need you to make the changes pointed on the comments above to approve your PR. Also, we would need a visual representation of the warning to users so they understand that they cannot access the test because they were not invited.

2024-03-12 23:06 UTC, KarinePistili commented on src/router/index.js
I think the behaviour should be to not be able to answer the test. And show an "unauthorized" warnining.

2024-03-12 23:06 UTC, KarinePistili commented on src/firebase/index.js
Please avoid to push unrelated code to the merge request topic. In this case we cannot accept such modification src/firebase/index.js because it would break the overall flow of the app and work only with emulator.

2024-03-12 23:06 UTC, KarinePistili commented on firestore-debug.log
Please avoid to push debug logs.

2024-03-13 07:00 UTC, skushagra9 commented on src/router/index.js
sure

2024-03-13 07:00 UTC, skushagra9 commented on src/firebase/index.js
ok

2024-04-04 03:50 UTC, closed without merging